name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        run: |
            mkdir -p temp_dir
            cp -r custom_components/h806sb/* temp_dir/
            cd temp_dir
            zip -r ../h806sb.zip .
            cd ..
            rm -rf temp_dir

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: h806sb.zip
          name: "Release ${{ github.ref_name }}"